config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'exams#index', as: :authenticated_root
  end
  root to: 'static_pages#home'

  resources :users, only: :show
  resources :exams do
    resources :results, only: [:show, :create]
  end
  
  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :questions, except: :index
    resources :courses
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize object.errors.count, "error" %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_result.html.erb
 <% if @exams.first %> 
  <% @exams.each do |exam| %>
    <%= exam.course.name %> |
    <% result = exam.result %>
    <% unless result.nil? %>
      Score: <%= result.score %>/<%= exam.course.questions.choice_question.count %> |
      Date: <%= exam.updated_at %>
      <%= link_to 'View', exam_result_path(exam, result),
                                          class: "btn btn-xs btn-info" %>
      <%= link_to 'Export', exam_result_path(exam, result, format: :csv),
                                          class: "btn btn-xs btn-primary" %>
      <% if can? :destroy, exam %>
        <%= link_to 'Destroy', exam, class: "btn btn-xs btn-danger",
                  method: :delete, data: {confirm: 'Are you sure?'} %>
      <% end %>
    <% end %></br>
  <% end %>
<% else %>
  Record not found
<% end %> 