config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'exams#index', as: :authenticated_root
  end
  root to: 'static_pages#home'

  resources :users, only: :show
  resources :exams do
    resources :results, only: [:show, :create]
  end
  
  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :questions, except: :index
    resources :courses
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  has_many :options, dependent: :destroy
  belongs_to :course

  accepts_nested_attributes_for :options

  validates :content, presence: true

  scope :choice_question, -> {where type_question: 'choice_question'}

  def is_choice_question?
    self.type_question == "choice_question"
  end

end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def show
    @question = Question.find params[:id]
    @options = @question.options
  end

  def new
    @course = Course.find params[:course_id]
    4.times {@question.options.build}
  end

  def create
    if @question.save
      flash[:notice] = 'Question has been created'
      redirect_to admin_course_path @question.course
    else
      render 'new'
    end
  end

  def edit
    @course = @question.course
  end

  def update
    if @question.update_attributes question_params
      redirect_to admin_course_path @question.course
    else
      render 'edit'
    end
  end

  def destroy
    @question.destroy
    flash[:success] = "Question deleted"
    redirect_to admin_course_path @question.course
  end

  private
  def question_params
    params.require(:question).permit :course_id, :type_question,
      :content, options_attributes: [:id, :content, :correct]
  end
end

app/views/admin/questions/_form.html.erb
<%= form_for [:admin, @question] do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.label :content, 'Question' %><br />
    <%= f.text_area :content, rows: 3 %><br />
  </div>
  <div id="type_question" class="radio">
    <%= f.radio_button :type_question, "choice_question", checked: true %> Choice question </br>
    <%= f.radio_button :type_question, "text_question" %> Text Question
  </div>
  <div id="answer-area">
    <%= f.fields_for :options do |builder| %>
      <div class="field">
        <%= builder.label :content, 'Option' %>
        <%= builder.text_field :content, class: 'form-control' %>
      </div>
      <div class="checkbox inline">
        <%= builder.check_box :correct %>
        <%= builder.label :correct, 'Correct?' %>
      </div>
    <% end %>
  </div>
  <%= f.hidden_field :course_id, value: @course.id%>
  <p><%= f.submit 'Submit', class: "btn btn-primary" %></p>
<% end %>
 
<script>
  $('#type_question input').on('change', function() {
    if(($('input[name="question[type_question]"]:checked',
        '#type_question').val()) == "text_question")
      $("#answer-area").hide();
    else $("#answer-area").show();
  });
</script>

app/views/admin/questions/_show.html.erb
<div class="content">
  <b>Question:</b>
  <div>
    <li class="list-group-item list-group-item-info">
      <%= @question.content %> </br>
    </li>
  </div>
  <% if @question.is_choice_question? %>
    <b>Answer :</b>
    <div>
      <table class="table table-bordered">
        <% @options.each do |option| %>
          <tr>
            <% unless option.correct %>
              <td><%= option.content %></td>    
            <% else %>
              <td class="success"><%= option.content %></td>
            <% end %>
          </tr>
        <% end %>
      </table>
    </div>
  <% end %>
  </br>
  <%= link_to 'Edit', edit_admin_question_path(@question), remote: true, class: "btn btn-warning" %>
</div>

app/views/admin/questions/edit.html.erb
<%= render 'form' %>

app/views/admin/questions/new.html.erb
<%= render 'form' %>

app/views/admin/questions/show.html.erb
<div class="col-md-10">
  <b>Question:</b> <%= @question.content %> </br>
  <% @options.each do |option| %>
    <b><%= option.correct %>: </b>
    <%= option.content %> </br>
  <% end %>
  <%= link_to 'Edit', edit_admin_question_path(@question) %>
  <%= link_to 'Delete', admin_question_path(@question),
          method: :delete, data: {confirm: 'Are you sure?'} %>
</div>