config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'exams#index', as: :authenticated_root
  end
  root to: 'static_pages#home'

  resources :users, only: :show
  resources :exams do
    resources :results, only: [:show, :create]
  end
  
  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :questions, except: :index
    resources :courses
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :exams
  
  mount_uploader :avatar, AvatarUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :normal, -> {where role: 'normal'}

  def slug
    name.to_s.downcase.gsub(" ", "-")  
  end

  def to_param
    "#{id}-#{slug}"
  end

  def is_admin?
    self.role == 'admin'
  end

  def search_with_course exams, course_name
    exams.joins(:course).merge Course.search_by_name course_name
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  
  def index
    @users = @users.normal.paginate page: params[:page]
  end

  def destroy
    @user.destroy
    flash[:notice] = 'User has been deleted'
    redirect_to admin_users_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def show
    @user = User.find params[:id]
    exams = params[:type] && params[:type] != 'all' ?
      @user.exams.send(params[:type]) : @user.exams
    @exams = @user.search_with_course exams, params[:search]
  end
end

app/views/admin/users/index.html.erb
<% provide :title, 'User list' %>
<h1>User list</h1>
<div class="col-sm-3 col-md-12">
  <%= will_paginate %>
  <ul class="list-group">
    <% @users.each do |user| %>
      <li class="list-group-item list-group-item-info">
        <b><%= link_to "#{user.name} (#{user.email})", user_path(user) %></b></br>
        Added <%= time_ago_in_words user.created_at %> ago.
        <%= link_to "Details", user_path(user),
                                 class: "btn btn-xs btn-info" %> |
        <%= link_to "Delete", admin_user_path(user),
                                 class: "btn btn-xs btn-danger",
                                 method: :delete,
                                 data: {confirm: 'Are you sure?'} %>
      </li>
    <% end %>
  </ul>
  <%= will_paginate %>
</div>