config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'exams#index', as: :authenticated_root
  end
  root to: 'static_pages#home'

  resources :users, only: :show
  resources :exams do
    resources :results, only: [:show, :create]
  end
  
  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :questions, except: :index
    resources :courses
  end
end

app/views/layouts/_header.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Examination System", root_path, id: "logo" %>
    <nav>
      <p class="navbar-text pull-right">
        <% if user_signed_in? %>          
          Hi <strong><%= link_to current_user.name, user_path(current_user) %></strong>.
          <% if current_user.is_admin? %>
            <%= link_to "User Manage", admin_users_path,
                class: 'navbar-link' %> |
            <%= link_to "Course Manage", admin_courses_path,
                class: 'navbar-link' %> |
          <% end %>
          <%= link_to 'Edit profile', edit_user_registration_path,
                class: 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete,
                class: 'navbar-link' %>

          <% if current_user.avatar.present? %>
            <div class="round-image-50">
              <%= image_tag(current_user.avatar.url) %>
            </div>
          <% else %>
            <div class="round-image-50"><%= image_tag('default.jpg') %></div>
          <% end %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path,
                class: 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, class: 'navbar-link'  %>
        <% end %>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application",
                                            "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
      <%= debug params if Rails.env.development? %>
    </div>
  </body>
</html>